-- MySQL Script generated by MySQL Workbench
-- Sun Jan 28 14:28:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema candixolotl
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema candixolotl
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `candixolotl` DEFAULT CHARACTER SET utf8 ;
USE `candixolotl` ;

-- -----------------------------------------------------
-- Table `candixolotl`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `candixolotl`.`Customer` (
  `idCustomer` INT NOT NULL DEFAULT c,
  `names` VARCHAR(30) NOT NULL,
  `last_names` VARCHAR(30) NOT NULL,
  `birth_date` DATE NOT NULL,
  `user_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `psw` VARCHAR(50) NOT NULL,
  `created_at` DATETIME GENERATED ALWAYS AS () VIRTUAL,
  PRIMARY KEY (`idCustomer`, `user_name`),
  UNIQUE INDEX `idCustomer_UNIQUE` (`idCustomer` ASC) VISIBLE,
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
