# Generated by Django 5.0.6 on 2024-08-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_item_serie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="serie",
            field=models.CharField(default="Uj61", max_length=4, unique=True),
        ),
    ]
