# Generated by Django 5.0.6 on 2024-08-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_item_serie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PEANUTS", "Cacahuate"),
                            ("CHOCOLATE", "Chocolate"),
                            ("GUMMIES", "Gomitas"),
                            ("SNACK", "Botana"),
                        ],
                        default="GUMMIES",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("AICHOLOTL", "aicholotl"),
                            ("VERO", "Vero"),
                            ("DE_LA_ROSA", "De la Rosa"),
                        ],
                        default="CANDIXOLOTL",
                        max_length=15,
                    ),
                ),
                (
                    "unit_grammage",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                ("units", models.IntegerField()),
                ("serie", models.CharField(default="aC49", max_length=4, unique=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "products",
            },
        ),
        migrations.RenameModel(
            old_name="Client",
            new_name="Customer",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
