# Generated by Django 5.0.6 on 2024-08-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_product_rename_client_customer_delete_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="serie",
            field=models.CharField(default="Am00", max_length=4, unique=True),
        ),
    ]
