# Generated by Django 5.0.6 on 2024-08-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_alter_product_serie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(
                choices=[
                    ("AIcholotl", "AICHOLOTL"),
                    ("Vero", "VERO"),
                    ("De la Rosa", "DE_LA_ROSA"),
                ],
                default="AIcholotl",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="kind",
            field=models.CharField(
                choices=[
                    ("Cacahuate", "PEANUTS"),
                    ("Chocolate", "CHOCOLATE"),
                    ("Gomitas", "GUMMIES"),
                    ("Botana", "SNACK"),
                    ("Dulce Mexicano", "MEXICAN_CANDY"),
                    ("Exótico", "EXOTIC"),
                ],
                default="GUMMIES",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="serie",
            field=models.CharField(default="sP91", max_length=4, unique=True),
        ),
    ]
